name: C2

on:
  push:
    branches: [ main ]
    paths:
      - 'laba_22/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'laba_22/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: go to laba_22 and build
      working-directory: ./laba_22
      run: make Makefile build
    - name: test
      working-directory: ./laba_22
      run: make Makefile mtest
