name: C3

on:
  push:
    branches: [ master ]
    paths:
      - 'LABA_2_2(c)/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'laba_2_2(c)/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: go to laba_2_2(c) and build
      working-directory: ./laba_2_2(c)
      run: make Makefile build
    - name: test
      working-directory: ./laba_2_2(c)
      run: make Makefile test
