name: C4

on:
  push:
    branches: [ master ]
    paths:
      - 'laba_3/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'laba_3/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: go to laba_3 and build
      working-directory: ./laba_3
      run: make Makefile build
    - name: test
      working-directory: ./laba_3
      run: make Makefile test
