name: C5

on:
  push:
    branches: [ main ]
    paths:
      - 'lab_4_1/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'lab_4_1/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: go to lab_4_1 and build
      working-directory: ./lab_4_1
      run: make Makefile build
    - name: test
      working-directory: ./lab_4_1
      run: make Makefile mtest
